import { motion } from "framer-motion";
import type { AnswerRecord, GameQuestion } from "../types/game";
import { AmbiosMark } from "./AmbiosMark";
import { CottonPlant, plantStageLabel } from "./CottonPlant";
import { performanceMessage } from "../utils/game";
import { AnimatedScore } from "./AnimatedScore";

export function FinalScreen({ score, correctCount, maxStreak, maxMultiplier, game, answers, onRestart, onCapture }: { score: number; correctCount: number; maxStreak: number; maxMultiplier: number; game: GameQuestion[]; answers: AnswerRecord[]; onRestart: () => void; onCapture: () => void }) {
  const errors = game.length - correctCount; const percentage = Math.round((correctCount / game.length) * 100); const finalStage = correctCount; const answerByQuestion = new Map(answers.map((answer) => [answer.questionId, answer]));
  return <motion.main className="final-screen" initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }}><AmbiosMark /><div className="completion-ring"><span>{correctCount}<small>/ 10</small></span><i>ACERTOS</i></div><p className="eyebrow">SEU CULTIVO</p><h1>RESULTADO<br /><em>REVELADO</em></h1><div className="final-score"><span>PONTUAÇÃO FINAL</span><AnimatedScore score={score} /></div><div className="result-stats"><span><b>{errors}</b> ERROS</span><span><b>×{maxMultiplier}</b> MAIOR MULTIPLICADOR</span><span><b>{maxStreak}</b> MAIOR SEQUÊNCIA</span></div><div className="final-plant"><CottonPlant stage={finalStage} /><div><span>ESTÁGIO DA PLANTA</span><strong>{plantStageLabel(finalStage)}</strong><small>{percentage}% DE DESENVOLVIMENTO</small></div></div><motion.button className="primary-button capture-button" onClick={onCapture} whileHover={{ scale: 1.025 }} whileTap={{ scale: .97 }}><span>RECEBER CONTEÚDOS AMBIOS</span><i>→</i></motion.button><p className="performance-message">{performanceMessage(score, correctCount)}</p><details className="review"><summary>REVISAR RESPOSTAS <b>↓</b></summary><div>{game.map((question, index) => { const answer = answerByQuestion.get(question.id); return <article key={question.id} className={answer?.isCorrect ? "review-correct" : "review-wrong"}><span>PERGUNTA {String(index + 1).padStart(2, "0")} · {answer?.isCorrect ? "CORRETA" : "INCORRETA"}</span><h3>{question.question}</h3><p><b>SUA RESPOSTA:</b> {answer ? question.answers[answer.selectedAnswer] : "Não respondida"}</p><p><b>RESPOSTA CORRETA:</b> {question.answers[question.correctAnswer]}</p><p>{question.explanation}</p></article>; })}</div></details><button className="text-button" onClick={onRestart}>DESENVOLVER OUTRA PLANTA</button><p className="footer-note">AMBIOS · CONHECIMENTO QUE REGENERA</p></motion.main>;
}
