import { motion } from "framer-motion";
import type { FormEvent } from "react";
import { AmbiosMark } from "./AmbiosMark";
import regenesis from "../assets/regenesis-wordmark-new.svg";
import { useRouletteGame, type Participant } from "../hooks/useRouletteGame";

const levelName = (level: number) => level === 7 ? "DESAFIO REGENESIS" : level < 3 ? "MUITO FÁCIL" : level < 5 ? "FÁCIL" : level === 5 ? "MÉDIO" : "DIFÍCIL";
export function RouletteGame() { const game = useRouletteGame();
 if (game.screen === "lead") return <Lead onStart={game.start} />;
 if (game.screen === "wheel") return <main className="roulette-screen premium-wheel"><header><AmbiosMark /><img src={regenesis} alt="Regenesis" /></header><p className="eyebrow">ROLETA REGENESIS</p><h1>GIRE E DESCUBRA<br /><em>SEU DESAFIO</em></h1><p>Um giro. Uma pergunta. Um desafio.</p><div className="wheel-wrap"><i className="wheel-pointer">▼</i><div className="wheel-halo" /><div className="wheel-rings" /><div className={`wheel ${game.spinning ? "spinning" : ""}`} style={{ transform: `rotate(${game.rotation}deg)` }}>{[1,2,3,4,5,6,7].map((n) => { const angle = (n - 1) * 360 / 7; return <b key={n} className={`segment segment-${n}`} style={{ transform: `rotate(${angle}deg)` }}><span style={{ transform: `rotate(${-game.rotation - angle}deg)` }}>{n}</span></b>; })}</div><div className="wheel-core"><small>AMBIOS.</small><img src={regenesis} alt="Regenesis" /></div></div><button className="primary-button" disabled={game.spinning} onClick={game.spin}><span>{game.spinning ? "GIRANDO..." : "GIRAR ROLETA"}</span><i>↻</i></button></main>;
 if (game.screen === "challengeReveal") return <main className={`reveal-screen ${game.wheelNumber === 7 ? "special" : ""}`}><AmbiosMark /><img src={regenesis} alt="Regenesis" />{game.wheelNumber === 7 ? <><p>VOCÊ CAIU NO</p><h1>DESAFIO<br /><em>REGENESIS!</em></h1><small>Prepare-se para o desafio máximo.</small></> : <><p>SEU DESAFIO É O</p><h1>Nº <em>{game.wheelNumber}</em></h1><small>NÍVEL {levelName(game.wheelNumber!)}</small></>}<button className="primary-button" onClick={() => game.setScreen("question")}><span>VER PERGUNTA</span><i>→</i></button></main>;
 if (game.screen === "question" && game.question) return <main className="roulette-question"><header><AmbiosMark compact /><img src={regenesis} alt="Regenesis" /></header><p className="eyebrow">DESAFIO Nº {game.wheelNumber} · {levelName(game.wheelNumber!)}</p><h1>{game.question.question}</h1><div className="answers">{game.question.answers.map((answer, index) => <button className={game.selected === index ? "answer selected" : "answer"} key={answer} onClick={() => game.setSelected(index)}><b>{"ABCD"[index]}</b>{answer}</button>)}</div><button className="primary-button" disabled={game.selected === null} onClick={game.confirm}><span>CONFIRMAR RESPOSTA</span><i>→</i></button></main>;
 return <main className={`roulette-result ${game.result ? "win" : ""}`}><AmbiosMark /><img src={regenesis} alt="Regenesis" /><p className="eyebrow">DESAFIO REGENESIS</p><h1>{game.result ? "ACERTOU!" : "QUASE!"}</h1><h2>{game.result ? "Mandou bem! Você venceu o Desafio Regenesis." : "Boa tentativa! Agora você já sabe mais sobre o Regenesis."}</h2>{!game.result && <p><b>RESPOSTA CORRETA:</b> {game.question?.answers[game.question.correctAnswer]}</p>}<p className="explanation">{game.question?.explanation}</p><button className="primary-button" onClick={game.next}><span>PRÓXIMO PARTICIPANTE</span><i>→</i></button></main>; }
function Lead({ onStart }: { onStart: (data: Participant) => void }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); onStart({ name: String(data.get("name")), phone: String(data.get("phone")), email: "", consent: Boolean(data.get("consent")) }); }; return <main className="roulette-lead"><AmbiosMark /><img src={regenesis} alt="Regenesis" /><p className="eyebrow">ROLETA REGENESIS</p><h1>PRONTO PARA<br /><em>O DESAFIO?</em></h1><p>Identifique-se e gire a roleta.</p><form onSubmit={submit}><input name="name" required placeholder="Nome" /><input name="phone" required inputMode="tel" placeholder="Telefone" /><label><input name="consent" required type="checkbox" /> Li e concordo com a Política de Privacidade.</label><button className="primary-button"><span>COMEÇAR DESAFIO</span><i>→</i></button></form></main>; }
